language: node_js
node_js:
  - "6"
  - "5"
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter'
notifications:
  email:
    recipients: prashant@noop.pw
    on_success: change
    on_failure: change

